{
 "title": "vBNG",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "pppoe active",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "accel-ppp_value",
     "query": "SELECT last(\"value\") FROM \"accel-ppp_value\" WHERE (\"type_instance\" = 'pppoe_active') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "pppoe_active" }
     ]
    }
   ]
  },
  {
   "title": "Control plane traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "vxlan200 transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"value\"),1s)*8 FROM \"interface_tx\" WHERE (\"instance\" = 'vxlan200' AND \"type\" = 'if_octets') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data plane traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "enp134s0f1 transmitted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "query": "SELECT derivative(mean(\"value\"),1s)*8 FROM \"interface_tx\" WHERE (\"instance\" = 'veth_gw_ns' AND \"type\" = 'if_octets') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "veth_gw_ns" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  }
 ]
}