---
- hosts: all
  vars:
    host_interface: "{{ ansible_default_ipv4.interface }}"
    run_mode: "deploy"
    setup_all: "no"
    setup_docker: "no"
    setup_redis: "yes"
    setup_pfcp_cp: "no"
    setup_accel_pppd: "no"

  tasks:
  - name: "Set up docker environment"
    include_tasks: tasks/setup_docker_env_tasks.yaml
    when: setup_all == "yes" or setup_docker == "yes"

  - name: "Remove docker internal network for inter-container communication"
    docker_network:
      name: "{{ docker_network_name }}"
      state: absent
    when: run_mode == "clean" or run_mode == "clean_deploy"

  - name: "Create docker internal network for inter-container communication"
    docker_network:
      name: "{{ docker_network_name }}"
      ipam_config:
        - subnet: "{{ docker_subnet }}"
    when: run_mode == "deploy" or run_mode == "clean_deploy"

  - name: "Create bng_cp folder to store CP config files"
    become: yes
    file:
      path: "/etc/bng_cp/"
      state: directory
      mode: '0755'
    when: run_mode == "deploy" or run_mode == "clean_deploy"

  - name: "Set up redis server container"
    include_tasks: tasks/setup_redis_tasks.yaml
    when: setup_all == "yes" or setup_redis == "yes"

  - name: "Set up PFCP control plane"
    include_tasks: tasks/setup_pfcp_cp_tasks.yaml
    when: setup_all == "yes" or setup_pfcp_cp == "yes"

    # This is done to avoid the next task to loop necessarily over the cp_instances variable
  - name: "Define accel_pppd_instances list when setup_accel_pppd is true"
    set_fact:
      accel_pppd_instances: "{{ cp_instances }}"
    when: setup_all == "yes" or setup_accel_pppd == "yes"

  - name: "Run tasks for setting up radius and accel_ppp"
    include_tasks: tasks/run_single_radius_accel-pppd_tasks_from_loop.yaml
    # loop: "{{ cp_instances }}"
    loop: "{{ accel_pppd_instances|default([]) }}"
    loop_control:
      loop_var: cp_instance
