version: '3'
services:
 dpdk-ip-pipeline-cli:
    build: ./bng-utils/dpdk-ip-pipeline-cli
    command: [ "--redis-host", "redis", "--redis-port", "6379", "--telnet-host-uplink", "telnet_uplink", "--telnet-port-uplink", "23", "--telnet-host-downlink", "telnet_downlink", "--telnet-port-downlink", "23" ]
    depends_on:
      - "redis"
      - "telnet_downlink"
      - "telnet_uplink"
      - "accel-pppd"
    networks:
      - 0_default_network
    restart: always
 redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - 0_default_network
    restart: always
 accel-pppd:
    build: ./docker-accel-ppp/accel-pppd
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/ppp:/dev/ppp"
    ports:
      - "2000-2001:2000-2001"
    networks:
      - 0_default_network
      - 1_accel_network
    mac_address: 00:00:00:01:00:00
    restart: always
    depends_on:
      - "redis"
    volumes:
      - /sbin/modprobe:/sbin/modprobe
      - ./config/accel-pppd/etc/accel-ppp.conf:/etc/accel-ppp.conf
    environment:
      - IFACE=eth1
 telnet_downlink:
    build: ./telnet
    networks:
      - 0_default_network
    restart: always
 telnet_uplink:
    build: ./telnet
    networks:
      - 0_default_network
    restart: always

networks:
  0_default_network:
    driver: bridge
  1_accel_network:
    driver: bridge
