---
- hosts: all
  vars:
    host_interface: "{{ ansible_default_ipv4.interface }}"

  tasks:
  - name: add Docker’s official GPG key and adding the apt repo
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add official docker repository for bionic to apt sources
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

  - name: update apt cache and install required packages (including docker)
    become: yes
    apt:
      update_cache: yes
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - virtualenv
      - python3-setuptools
      - aptitude
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
      - bridge-utils
      - linux-headers-generic
      - build-essential

  - name: install docker and docker-compose python modules
    pip:
      name:
        - docker-compose
        - docker
      executable: pip3

  - name: "add the user {{ ansible_user_id }} to the group 'docker'"
    become: yes
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    register: docker_user_add

  - name: Reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection
    when: docker_user_add changed

  - name: "Create bng_cp folder for redis/bngc files"
    become: yes
    file:
      path: "/etc/bng_cp/"
      state: directory
      mode: '0755'
    when: run_mode == "deploy" or run_mode == "clean_deploy"

  - name: "generate bngc.json config for PFCP control plane application"
    become: yes
    template:
      src: bngc.j2
      dest: "/etc/bng_cp/bngc.json"
    when: run_mode == "deploy" or run_mode == "clean_deploy"

  - name: "stop and remove PFCP BNG CP docker container"
    docker_container:
      state: absent
      name: "pfcp-bng-cp"
    when: run_mode == "clean_deploy" or run_mode == "clean"

  - name: "Start PFCP BNG CP application container"
    docker_container:
      name: "pfcp-bng-cp"
      image: "bisdn/pfcp-bng-cp"
      network_mode: host
      capabilities:
        - "SYS_NICE"
        - "NET_ADMIN"
      env:
        BNGC_IP: "{{ bngc_ip_addr }}"
        BNGC_NETMASK_BITS: "{{ net_prefix }}"
        BNGC_HOST_INTERFACE: "{{ host_interface }}"
      volumes:
        - /etc/bng_cp/bngc.json:/opt/bng-pfcp/build/bngc/build/bngc.json
    when: run_mode == "deploy" or run_mode == "clean_deploy"
