---
- hosts: all
  vars:
    # bngc_ip_addr can be set to the same address as the host or to a new one
    # in the same subnet
    bngc_ip_addr: "{{ ansible_default_ipv4.address }}"
    # bngc_ip_addr: "10.0.100.221"
    net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
    net_prefix: "{{ net_mask | ipaddr('prefix') }}"
    host_interface: "{{ ansible_default_ipv4.interface }}"

  tasks:
  - name: "Create bng_cp folder for redis/bngc files"
    become: yes
    file:
      path: "/etc/bng_cp/"
      state: directory
      mode: '0755'

  - name: "copy redis.conf to /etc/bng_cp/redis.conf in host"
    become: yes
    copy:
      src: "redis.conf"
      dest: "/etc/bng_cp/"
      force: yes

  - name: "generate bngc.json config for PFCP control plane application"
    become: yes
    template:
      src: bngc.j2
      dest: "/etc/bng_cp/bngc.json"

  - name: "stop and remove redis docker container for bngc control plane"
    #become: yes
    docker_container:
      state: absent
      name: redis
    when: run_mode == "clean_deploy"

  - name: "Create docker internal network for inter-container communication"
    docker_network:
      name: "{{ docker_network_name }}"
      ipam_config:
        - subnet: "{{ docker_subnet }}"

  - name: "start containerized redis with docker for all control plane"
    #become: yes
    docker_container:
      name: redis
      image: "redis:alpine"
      command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
      ports: "{{ redis_port }}:{{ redis_port }}"
      state: started
      volumes:
        - /etc/bng_cp/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        - name: "{{ docker_network_name }}"

  - name: "stop and remove PFCP BNG CP docker container"
    docker_container:
      state: absent
      name: "pfcp-bng-cp"
    when: run_mode == "clean_deploy"

  - name: "Start PFCP BNG CP application container"
    docker_container:
      name: "pfcp-bng-cp"
      image: "bisdn/pfcp-bng-cp"
      network_mode: host
      capabilities:
        - "SYS_NICE"
        # - "NET_ADMIN" # Uncomment to have permission to add address below
      env:
        # Uncomment these variables to add the BNGC_IP address to BNGC_HOST_INTERFACE
        # BNGC_IP: "{{ bngc_ip_addr }}"
        # BNGC_NETMASK_BITS: "{{ net_prefix }}"
        # BNGC_HOST_INTERFACE: "{{ host_interface }}"
      volumes:
        - /etc/bng_cp/bngc.json:/opt/bng-pfcp/build/bngc/build/bngc.json
